version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digitalMonyHouse-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dmh-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak-digitalMonyHouse
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: digitalMonyHouse-db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - dmh-network
    command: start-dev
    depends_on:
      - mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch-digitalMonyHouse
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=admin
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - dmh-network
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.16.5
    container_name: logstash
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    ports:
      - "5044:5044"
    networks:
      - dmh-network
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - C:/Users/Alejo/Documents/proyectofinal-dh-backend/logs:/logs

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - dmh-network

networks:
  dmh-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  keycloak-data:
    driver: local
  elasticsearch-data:
    driver: local