services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digitalMonyHouse-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    networks:
      - dmh-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.25"
        reservations:
          memory: 256m
          cpus: "0.1"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch-digitalMonyHouse
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=admin
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - dmh-network
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
        reservations:
          memory: 512m
          cpus: "0.25"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.16.5
    container_name: logstash
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    ports:
      - "5044:5044"
    networks:
      - dmh-network
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - app-logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.25"
        reservations:
          memory: 256m
          cpus: "0.1"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - dmh-network
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.25"
        reservations:
          memory: 256m
          cpus: "0.1"

  redis:
    image: redis:7.0
    container_name: redis-digitalMonyHouse
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dmh-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.2"
        reservations:
          memory: 128m
          cpus: "0.1"

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8082:8082"
    volumes:
      - ./auth-service:/usr/src/app
      - app-logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dmh-network
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.2"
        reservations:
          memory: 128m
          cpus: "0.1"

  config-service:
    build:
      context: ./configServer
    ports:
      - "8888:8888"
    volumes:
      - app-logs:/app/logs
    networks:
      - dmh-network
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.2"
        reservations:
          memory: 128m
          cpus: "0.1"

  cuenta-service:
    build:
      context: ./cuenta-service
    ports:
      - "8084:8084"
    volumes:
      - ./cuenta-service:/usr/src/app
      - app-logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.2"
        reservations:
          memory: 128m
          cpus: "0.1"
    networks:
      - dmh-network

  service-api-gateway:
    build:
      context: ./service-api-gateway
    ports:
      - "8081:8081"
    volumes:
      - app-logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.2"
        reservations:
          memory: 128m
          cpus: "0.1"
    networks:
      - dmh-network

  servicio-eurekaserver:
    build:
      context: ./servicio-eurekaServer
    ports:
      - "8761:8761"
    volumes:
      - app-logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.2"
        reservations:
          memory: 128m
          cpus: "0.1"
    networks:
      - dmh-network

  servicio-tarjetas:
    build:
      context: ./servicio-tarjetas
    ports:
      - "8086:8086"
    volumes:
      - ./servicio-tarjetas:/usr/src/app
      - app-logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.2"
        reservations:
          memory: 128m
          cpus: "0.1"
    networks:
      - dmh-network

  servicio-transacciones:
    build:
      context: ./servicio-transacciones
    ports:
      - "8085:8085"
    volumes:
      - ./servicio-transacciones:/usr/src/app
      - app-logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.2"
        reservations:
          memory: 128m
          cpus: "0.1"
    networks:
      - dmh-network

  servicio-usuarios:
    build:
      context: ./servicio-usuarios
    ports:
      - "8083:8083"
    volumes:
      - ./servicio-usuarios:/usr/src/app
      - app-logs:/app/logs
    networks:
      - dmh-network
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.2"
        reservations:
          memory: 128m
          cpus: "0.1"

networks:
  dmh-network:
    driver: bridge

volumes:
  app-logs:
  mysql-data:
    driver: local
  elasticsearch-data:
    driver: local
  redis-data:
    driver: local