spring:
  application:
    name: servicio-usuarios
  datasource:
    url: jdbc:mysql://localhost:3306/digitalMonyHouse-db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev  # Cambiar a prod o test según sea el caso q tengo en el momento o pinte no cambia nada solo data
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8082

# Configuración de Actuator para monitoreo y exposición de métricas
management:
  endpoints:
    web:
      exposure:
        include: '*'   # Exponer todos los endpoints de actuator
  info:
    env:
      enabled: true    # Exponer información del entorno
  health:
    show-details: always  # Mostrar detalles completos en el endpoint health

# Configuración de logging
logging:
  level:
    org.springframework.web: INFO    # Configuración de nivel de log para Spring Web
    org.hibernate.SQL: DEBUG          # Mostrar las consultas SQL de Hibernate
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Para ver valores de parámetros de las consultas
